---
title: "ST34 clonal analysis"
author: "Joao Carlos Gomes-Neto"
date: "3/5/2021"
output: html_document
---

Load packages

```{r, include = FALSE}
# Load packages

library(tidyverse)
library(skimr)
library(RColorBrewer)
library(gridExtra)
library(lattice)
library(ggpubr)
library(vegan)
library(reshape2)
library(ggrepel)
library(ggnewscale)
library(forcats)
library(naniar)
library(data.table)
library(rARPACK)
library(logisticPCA)
library(cluster)
library(factoextra)
library(NbClust)
library(plotly)
```

Generating the dataset and plot BAPS1-6 haplotype analysis

```{r, include = FALSE}
# Enter MLST results

mlst <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'/'), "[", 3)
s1 <- mlst %>% separate(id2, c("id", "day"), sep = "\\.")

# Select columns of interest

s2 <- s1 %>%
          select(id, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?")

# QC the data

skim(s2)

# st

s2$st <- ifelse(s2$ST == 34, "ST34", "Other STs")

# Create data1 

data1 <- s2 

####################################################################

# Enter group1-Baps

# Enter the data, create a new column for group, and generate the id column
data3 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_1/input_data/roary_output_gr1.fastbaps_l6.csv")
data3$group <- "group_1"
colnames(data3)[1] <- "id"

###########################################################################

# Enter group2-Baps

# Enter the data, create a new column for group, and generate the id column

data4 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr2.fastbaps_l6.csv")
data4$group <- "group_2"
colnames(data4)[1] <- "id"

###########################################################################

# Enter group3-Baps
# Enter the data, create a new column for group, and generate the id column

data5 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr3.fastbaps_l6.csv")
data5$group <- "group_3"
colnames(data5)[1] <- "id"

###########################################################################

# Enter group4-Baps
# Enter the data, create a new column for group, and generate the id column

data6 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr4.fastbaps_l6.csv")
data6$group <- "group_4"
colnames(data6)[1] <- "id"

###########################################################################

# Enter group5-Baps
# Enter the data, create a new column for group, and generate the id column

data7 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr5.fastbaps_l6.csv")
data7$group <- "group_5"
colnames(data7)[1] <- "id"

###########################################################################

# Enter group6-Baps
# Enter the data, create a new column for group, and generate the id column

data8 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr6.fastbaps_l6.csv")
data8$group <- "group_6"
colnames(data8)[1] <- "id"

###########################################################################

# Enter group7-Baps
# Enter the data, create a new column for group, and generate the id column

data9 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr7.fastbaps_l6.csv")
data9$group <- "group_7"
colnames(data9)[1] <- "id"

###########################################################################

# Enter group8-Baps
# Enter the data, create a new column for group, and generate the id column

data10 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr8.fastbaps_l6.csv")
data10$group <- "group_8"
colnames(data10)[1] <- "id"

###########################################################################

# Enter group9-Baps
# Enter the data, create a new column for group, and generate the id column

data11 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr9.fastbaps_l6.csv")
data11$group <- "group_9"
colnames(data11)[1] <- "id"

###########################################################################

# Enter group10-Baps
# Enter the data, create a new column for group, and generate the id column

data12 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr10.fastbaps_l6.csv")
data12$group <- "group_10"
colnames(data12)[1] <- "id"

###########################################################################

# Enter group11-Baps
# Enter the data, create a new column for group, and generate the id column

data13 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr11.fastbaps_l6.csv")
data13$group <- "group_11"
colnames(data13)[1] <- "id"

###########################################################################

# Enter group12-Baps
# Enter the data, create a new column for group, and generate the id column

data14 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr12.fastbaps_l6.csv")
data14$group <- "group_12"
colnames(data14)[1] <- "id"

###########################################################################

# Enter group13-Baps
# Enter the data, create a new column for group, and generate the id column

data15 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr13.fastbaps_l6.csv")
data15$group <- "group_13"
colnames(data15)[1] <- "id"

###########################################################################

# Enter group14-Baps
# Enter the data, create a new column for group, and generate the id column

data16 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr14.fastbaps_l6.csv")
data16$group <- "group_14"
colnames(data16)[1] <- "id"

###########################################################################

# Enter group15-Baps
# Enter the data, create a new column for group, and generate the id column

data17 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr15.fastbaps_l6.csv")
data17$group <- "group_15"
colnames(data17)[1] <- "id"

###########################################################################

# Enter group16-Baps
# Enter the data, create a new column for group, and generate the id column

data18 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr16.fastbaps_l6.csv")
data18$group <- "group_16"
colnames(data18)[1] <- "id"

###########################################################################

# Enter group17-Baps
# Enter the data, create a new column for group, and generate the id column

data19 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr17.fastbaps_l6.csv")
data19$group <- "group_17"
colnames(data19)[1] <- "id"

###########################################################################

# Enter group18-Baps
# Enter the data, create a new column for group, and generate the id column

data20 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr18.fastbaps_l6.csv")
data20$group <- "group_18"
colnames(data20)[1] <- "id"

###########################################################################

# Enter group19-Baps
# Enter the data, create a new column for group, and generate the id column

data21 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr19.fastbaps_l6.csv")
data21$group <- "group_19"
colnames(data21)[1] <- "id"

###########################################################################

# Enter group20-Baps
# Enter the data, create a new column for group, and generate the id column

data22 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/roary_output_gr20.fastbaps_l6.csv")
data22$group <- "group_20"
colnames(data22)[1] <- "id"

###########################################################################

# First merge all Baps datasets 

data_baps <- bind_rows(data3, data4, data5, data6, data7, data8,
                       data9, data10, data11, data12, data13, data14, 
                       data15, data16, data17, data18, data19, data20, 
                       data21, data22)

colnames(data_baps)[2:7] <- c("BAPS1", "BAPS2", "BAPS3", "BAPS4", "BAPS5", "BAPS6")

############################################################################

# Merge data1 and data2

data23 <- left_join(data1, data_baps, on = "id")

# drop missing values

d4 <- data23 %>% drop_na()

d4 <- d4 %>% mutate(BAPS1 = as.factor(BAPS1))
d4 <- d4 %>% mutate(BAPS2 = as.factor(BAPS2))
d4 <- d4 %>% mutate(BAPS3 = as.factor(BAPS3))
d4 <- d4 %>% mutate(BAPS4 = as.factor(BAPS4))
d4 <- d4 %>% mutate(BAPS5 = as.factor(BAPS5))
d4 <- d4 %>% mutate(BAPS6 = as.factor(BAPS6))

# plot data

# Baps based diversity 

# Baps1
baps1 <- d4 %>%
              select(st, BAPS1) %>%
              drop_na(st, BAPS1) %>%
              group_by(st, BAPS1) %>%
              summarise(n = n()) %>%
              mutate(total = sum(n)) %>% 
              mutate(prop = n/total*100) %>%
              mutate(group = "BAPS1") %>%
              rename(baps = BAPS1)

# Baps2
baps2 <- d4 %>%
              select(st, BAPS2) %>%
              drop_na(st, BAPS2) %>%
              group_by(st, BAPS2) %>%
              summarise(n = n()) %>%
              mutate(total = sum(n)) %>% 
              mutate(prop = n/total*100) %>%
              mutate(group = "BAPS2") %>%
              rename(baps = BAPS2)

# Baps3
baps3 <- d4 %>%
              select(st, BAPS3) %>%
              drop_na(st, BAPS3) %>%
              group_by(st, BAPS3) %>%
              summarise(n = n()) %>%
              mutate(total = sum(n)) %>% 
              mutate(prop = n/total*100) %>%
              mutate(group = "BAPS3") %>%
              rename(baps = BAPS3)


# Baps4
baps4 <- d4 %>%
              select(st, BAPS4) %>%
              drop_na(st, BAPS4) %>%
              group_by(st, BAPS4) %>%
              summarise(n = n()) %>%
              mutate(total = sum(n)) %>% 
              mutate(prop = n/total*100) %>%
              mutate(group = "BAPS4") %>%
              rename(baps = BAPS4)

# Baps5
baps5 <- d4 %>%
              select(st, BAPS5) %>%
              drop_na(st, BAPS5) %>%
              group_by(st, BAPS5) %>%
              summarise(n = n()) %>%
              mutate(total = sum(n)) %>% 
              mutate(prop = n/total*100) %>%
              mutate(group = "BAPS5") %>%
              rename(baps = BAPS5)

              # Baps6
baps6 <- d4 %>%
              select(st, BAPS6) %>%
              drop_na(st, BAPS6) %>%
              group_by(st, BAPS6) %>%
              summarise(n = n()) %>%
              mutate(total = sum(n)) %>% 
              mutate(prop = n/total*100) %>%
              mutate(group = "BAPS6") %>%
              rename(baps = BAPS6)

# Concatenate all datasets

d5 <- rbind(baps1, baps2, baps3, baps4, baps5, baps6)
d5$group <- factor(d5$group, levels=c("BAPS1", "BAPS2", "BAPS3",
                                              "BAPS4", "BAPS5", "BAPS6"))

# plot data
d5 <- d5 %>% mutate(baps = as.numeric(baps))
plot1 <- ggplot(d5, aes(x = baps, y = prop, fill = st)) + ylim(0, 100) +
  theme_bw() +
  geom_col(position = "dodge")+
  xlab("BAPS sub-groups (haplotypes)") +
  ylab("Proportion") +
    theme(axis.text.x = element_text(angle = 0, size = 25)) +
  theme(axis.title.x = element_text(size = 35, face = "bold")) +
  theme(axis.title.y = element_text(size = 35, face = "bold")) +
  theme(axis.text.y = element_text(angle = 0, hjust = 1, size = 25)) +
  theme(legend.title=element_text(size=35, face = "bold"))+
  theme(legend.text=element_text(size=25)) +
  scale_fill_manual(name = "ST", values=c("gray", "darkblue")) +
  theme(strip.text.x = element_text(size = 35)) +
  facet_wrap(~group, ncol = 2) 
plot1
```
