---
title: "Typhimurium group 4 pangenome"
author: "Joao Carlos Gomes-Neto"
date: "3/10/2021"
output: html_document
---

Load packages

```{r, include = FALSE}
# Load packages

library(tidyverse)
library(skimr)
library(RColorBrewer)
library(gridExtra)
library(lattice)
library(ggpubr)
library(vegan)
library(reshape2)
library(ggrepel)
library(ggnewscale)
library(forcats)
library(naniar)
library(data.table)
library(rARPACK)
library(logisticPCA)
library(cluster)
library(factoextra)
library(NbClust)
library(plotly)
```

Generating metadata for Salmonella Typhimurium heatmap plot

```{r, include = FALSE}

# Enter group1-Baps

# Enter the data, create a new column for group, and generate the id column
data4 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_4/input_data/roary_output_gr4.fastbaps_l6.csv")
data4$group <- "group_4"
colnames(data4)[1:2] <- c("id", "baps_1")

d1 <- data4 %>% select(id, baps_1, group)
###########################################################################
# Enter MLST results

mlst <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'/'), "[", 3)
s1 <- mlst %>% separate(id2, c("id", "day"), sep = "\\.")

# Select columns of interest

s2 <- s1 %>%
          select(id, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?")

# QC the data

skim(s2)

# st

s2$st <- ifelse(s2$ST == 19, "ST19", 
                   ifelse(s2$ST == 34, "ST34", 
                          ifelse(s2$ST == 36, "ST36",
                                 ifelse(s2$ST == 313, "ST313", "Other STs"))))

# Create data1 

d2 <- s2 

####################################################################

# Enter SISTR results

sistr <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/sistr_all.csv')

# QC the data 

skim(sistr)

# Select columns 

sis1 <- sistr %>%
            select(genome, cgmlst_ST, serovar_cgmlst) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") %>%
                rename(id = genome)

d3 <- sis1 

d3 <- mutate(d3, cgmlst = ifelse(cgmlst_ST %in% 1652656062, "cgMLST 1652656062",
                                     ifelse(cgmlst_ST %in% 860079270, "cgMLST 860079270", "Other cgMLSTs")))
##########################################################################
# KMER

data1 <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_4/kmer_matrix/kmer_group_4_typhimurium.csv')

#  Non-supervised kmeans clustering analysis

cluster_data <- data1 %>% select(tSNE1, tSNE2)

# combining both approaches we determine that 2 clusters are enough 
set.seed(123)
km.final <- kmeans(cluster_data, 6)
data1$kmer_cluster <- km.final$cluster
data1$kmer_cluster <- as.factor(data1$kmer_cluster)

# select the column we need

d4 <- data1 %>% select(id, kmer_cluster)
##################################################################################

# SNP

data1 <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_4/snp_matrix/snp_group_4_typhimurium.csv')

#  Non-supervised kmeans clustering analysis

cluster_data <- data1 %>% select(tSNE1, tSNE2)

# combining both approaches we determine that 2 clusters are enough 
set.seed(123)
km.final <- kmeans(cluster_data, 6)
data1$snp_cluster <- km.final$cluster
data1$snp_cluster <- as.factor(data1$snp_cluster)

# filter the column

d5 <- data1 %>% select(id, snp_cluster)

####################################################################################
#############################################################################################

# PCA CLUSTER

data1 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_4/pca_group_4/cluster2.csv")

d6 <- data1 %>% select(-X1)
#############################################################################################
#############################################################################################

# combining all datasets

d8 <- left_join(d1, d2, on = "id")
d9 <- left_join(d8, d3, on = "id")
d10 <- left_join(d9, d4, on = "id")
d11 <- left_join(d10, d5, on = "id")
d12 <- left_join(d11, d6, on = "id")

# if NA for ST call others 

d14 <- d12 %>% mutate(st = replace_na(st, "Other STs"))
d15 <- d14 %>% mutate(pca_cluster = cluster) %>% select(-cluster)
d15 <- d15 %>% mutate(baps_1 = as.factor(baps_1))
d15 <- d15 %>% mutate(pca_cluster = as.factor(pca_cluster))
d15 <- d15 %>% select(id, baps_1, st, cgmlst, kmer_cluster, snp_cluster, pca_cluster)

#############################################################################################
#############################################################################################

# Getting the AMR data 

abx1 <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/sabricate_resfinder_output.csv')
abx1$id2 <- sapply(strsplit(as.character(abx1$'#FILE'),'/'), "[", 3)
abx1 <- abx1 %>% separate(id2, c("id", "garbage"), sep = "\\.")
abx1 <- abx1 %>% mutate(gene = GENE)
abx2 <- abx1 %>% select(id, gene)

# eliminate genes with double or more counts

abx3 <- abx2 %>% group_by(id, gene) %>% count()
abx4 <- abx3 %>% filter(n <= 1)

# spread the data

abx5 <- spread(abx4, key = gene, value = n)

# input zeros for replacing NAs

abx5[is.na(abx5)] <- 0

# merge with d15

d16 <- left_join(d15, abx5, on = "id")
d17 <- column_to_rownames(d16, var = "id")

# export file as csv

group_1_abx <- d17
#write.csv(group_1_abx, "~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_1/input_data/group_1_abx.csv")

# filter genes that we need

d18 <- group_1_abx %>% select(baps_1, st, cgmlst, kmer_cluster, snp_cluster, pca_cluster,
                                             `aac(3)-Ib_1`, `aac(6')-Iaa_1`, aadA2_1, `ant(3'')-Ia_1`, `aph(3'')-Ib_5`,
                                             `aph(6)-Id_1`, `blaCARB-2_1`, `blaTEM-1B_1`, catA1_1,
                                             dfrA1_10, floR_2, sul1_5, sul1_10, sul2_2, sul2_3, sul2_6,
                                             `tet(A)_6`, `tet(B)_2`, `tet(G)_2`, `mdf(A)_1`)

d19 <- rownames_to_column(d18, var = "id")
#############################################################################################
#############################################################################################

# Getting the plasmid data 

x1 <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/global_input_data/sabricate_plasmidfinder_output.csv')
x1$id2 <- sapply(strsplit(as.character(x1$'#FILE'),'/'), "[", 3)
x1 <- x1 %>% separate(id2, c("id", "garbage"), sep = "\\.")
x1 <- x1 %>% mutate(gene = GENE)
x2 <- x1 %>% select(id, gene)

# eliminate genes with double or more counts

x3 <- x2 %>% group_by(id, gene) %>% count()
x4 <- x3 %>% filter(n <= 1)

# spread the data

x5 <- spread(x4, key = gene, value = n)

# input zeros for replacing NAs

x5[is.na(x5)] <- 0

# merge with d15

d16 <- left_join(d15, x5, on = "id")
d17 <- column_to_rownames(d16, var = "id")
d17[is.na(d17)] <- 0

# export file as csv

group_1_plasmid <- d17
#write.csv(group_1_plasmid, "~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_1/input_data/group_1_plasmid.csv")

# filter plasmids that we need

d18b <- group_1_plasmid %>% select(ColRNAI_1, `IncA/C2_1`, `IncFIB(S)_1`, `IncFII(S)_1`, IncQ1_1)

d19b <- rownames_to_column(d18b, var = "id")
######################################################################################
######################################################################################
######################################################################################

# combine AMR and plasmids into one dataset

d20 <- left_join(d19, d19b, on = "id")
#d20 <- column_to_rownames(d20, var = "id")

#####################################################################################
#####################################################################################
################################################################################
################################################################################
################################################################################

# enter Rtab file and select genes needed

d1 <- read_tsv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_4/input_data/gene_presence_absence.Rtab')

# set Genes as rownames

d1 <- column_to_rownames(d1, var = "Gene") 

d1$Gene <- NULL

# Transpose it

d2 <- transpose(d1)

# Add column and rownames

rownames(d2) <- colnames(d1)
colnames(d2) <- rownames(d1)

# Reset id to colnames

d3 <- rownames_to_column(d2, "id")

# List of targeted genes 

# metal resistance - SGI3-4

metals <- c("pcoA", "pcoB", "pcoC", "pcoD", "pcoE", "pcoG", "pcoR", "pcoS", "pco",
            "silA", "silB", "silC", "silE", "silP", "silR", "silS", "sil",
            "cusA", "cusB", "cusC", "cusF", "cusR", "cusS", "cus",
            "arsA", "arsB", "arsC", "arsD", "arsR", "ars",
            "merA", "merC", "merP", "merR", "merT",
            "zitB", 
            "zntA", "zntB", "zntR")

######################################################################

d4 <- d3 %>% select("id", contains(metals))

#remove_genes <- c("cusA_2", "cusB_2", "cusC_1", "cusC_2", "dcuS", "dcuS_1", "cusS_2", "arsA",
                 # "arsC_1", "arsC_2", "arsC_3", "arsD", "arsR2", "arsH", "merR1", "merT_2", "merT_1", 
                 # "zitB_1", "zntA_1", "zntB_1", "zntB_2", "zntR_2", "zntR_1")
#d5 <- d4 %>% select(!remove_genes)

# merge with d20

d21 <- left_join(d20, d4, on = "id")
d21[is.na(d21)] <- 0
lociPopStr_st34 <- column_to_rownames(d21, var = "id")
write.csv(lociPopStr_st34, "~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/typhimurium/group_4/input_data/lociPopStr_st34.csv")
```