---
title: "AMR and plasmid for Infantis"
author: "Joao Carlos Gomes-Neto"
date: "3/7/2021"
output: html_document
---
Load packages

```{r, include = FALSE}
# Load packages

library(tidyverse)
library(skimr)
library(RColorBrewer)
library(gridExtra)
library(lattice)
library(ggpubr)
library(vegan)
library(reshape2)
library(ggrepel)
library(ggnewscale)
library(forcats)
library(naniar)
library(data.table)
library(rARPACK)
library(logisticPCA)
library(cluster)
library(factoextra)
library(NbClust)
library(plotly)
library(visdat)
library(ggtree)
library(Rtsne)
```

generating the population structure metadata file

```{r, include = FALSE}
# enter metadata

d1 <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/metadata_cleaned_final_new.csv')

# rename variables

d2 <- d1 %>% select(id, collection_date, source)

# Combine all years less than 2015 into one group

d2 <- d2 %>%  mutate_all(na_if, "missing")

# change NA in the year column to zero

d2$collection_date[is.na(d2$collection_date)] <- 0

# transform year to numeric

d2 <- d2 %>% mutate(collection_date = as.numeric(collection_date))

# create a new column called Year

d2 <- mutate(d2, year = ifelse(collection_date == 2016, "2016",
                                    ifelse(collection_date == 2017, "2017",
                                            ifelse(collection_date == 2018, "2018",
                                                      ifelse(collection_date == 2019, "2019",
                                                             "<= 2015"
                                           )))))

# check for missing values 

vis_miss(d2)

# filter only needed columns 

d3b <- d2 %>% select(id, year, source)

##########################################################################
##########################################################################
##########################################################################

#############################################

# BAPS1

baps <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/fastbaps_partition_baps_prior_l6.csv')

# Changing column names 

colnames(baps)[1:2] <- c("id", "baps_1") 

# Select colunms id and baps_1
b1 <- baps %>% 
              select(id, baps_1)


d1 <- b1

#############################################################################################

# ST

# enter mlst data 
mlst <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'_'), "[", 1)

# Select columns of interest

s1 <- mlst %>%
          select(id2, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") %>%
                  rename(id = id2)

# st

s1$st <- ifelse(s1$ST == 32, "ST32", "Other STs")

d2 <- s1

d2 <- d2 %>% select(-ST)

#############################################################################################

# CGMLST

# Enter SISTR results

sistr <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/sistr_all.csv')

# QC the data 

skim(sistr)

# Generate the id column 

sistr$id <- sapply(strsplit(as.character(sistr$genome),'_'), "[", 1)

# Select columns 

sis1 <- sistr %>%
            select(id, cgmlst_ST, serovar_cgmlst) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") 

sis1$serovar <- ifelse(sis1$serovar_cgmlst == "Infantis", "Infantis",
                            "Other serovars")

sis1 <- mutate(sis1, cgmlst = ifelse(cgmlst_ST %in% 2242423463, "cgMLST 2242423463",
                                            "Other cgMLSTs"))

d3 <- sis1

d3 <- d3 %>% select(id, cgmlst)

#############################################################################################

# merge datasets

d4 <- left_join(d1, d2, on = "id")
d5 <- left_join(d4, d3, on = "id")

# replace NA for STs

d6 <- d5 %>% mutate(st = replace_na(st, "Other STs"))

##########################################################################################
##########################################################################################
##########################################################################################

# Getting the AMR data 

abx1 <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/sabricate_resfinder_output.csv')
abx1$id2 <- sapply(strsplit(as.character(abx1$'#FILE'),'/'), "[", 3)
abx1$id <- sapply(strsplit(as.character(abx1$id2),'_'), "[", 1)
abx1 <- abx1 %>% mutate(gene = GENE)
abx2 <- abx1 %>% select(id, gene)

# eliminate genes with double or more counts

abx3 <- abx2 %>% group_by(id, gene) %>% count()
abx4 <- abx3 %>% filter(n <= 1)

# spread the data

abx5 <- spread(abx4, key = gene, value = n)

# input zeros for replacing NAs

abx5[is.na(abx5)] <- 0

# filter genes that we need

abx6 <- abx5 %>% select(`aac(3)-IVa_1`, `aac(6')-Iaa_1`, 
                        `aph(3')-Ia_7`, 
                        `ant(3'')-Ia_1`,
                        `aph(4)-Ia_1`,
                        `blaCTX-M-65_1`,
                        dfrA14_5,
                        floR_2,
                        fosA3_1,
                        `mdf(A)_1`,
                        sul1_5,
                        `tet(A)_6`)


# export file as csv

abx6 <- column_to_rownames(abx6, var = "id")
infantis_abx <- abx6
write.csv(infantis_abx, "~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/infantis_abx.csv")

# generate another data file

abx7 <- abx5 %>% select(`aac(3)-IVa_1`, `aac(6')-Iaa_1`, 
                        `aph(3')-Ia_7`, 
                        `ant(3'')-Ia_1`,
                        `aph(4)-Ia_1`,
                        `blaCTX-M-65_1`,
                        dfrA14_5,
                        floR_2,
                        fosA3_1,
                        `mdf(A)_1`,
                        sul1_5,
                        `tet(A)_6`)

#############################################################################################
#############################################################################################
# Getting the plasmid data 

x1 <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/sabricate_plasmidfinder_output.csv')
x1$id2 <- sapply(strsplit(as.character(x1$'#FILE'),'/'), "[", 3)
x1$id <- sapply(strsplit(as.character(x1$id2),'_'), "[", 1)
x1 <- x1 %>% mutate(gene = GENE)
x2 <- x1 %>% select(id, gene)

# eliminate genes with double or more counts

x3 <- x2 %>% group_by(id, gene) %>% count()
x4 <- x3 %>% filter(n <= 1)

# spread the data

x5 <- spread(x4, key = gene, value = n)

# input zeros for replacing NAs

x5[is.na(x5)] <- 0

# filter plasmids that we need

x6 <- x5 %>% select(ColpVC_1, ColRNAI_1, `IncA/C2_1`,
                    IncFIA_1, `IncFIB(AP001918)_1`,
                    `IncFIB(K)_1_Kpn3`, `IncFIC(FII)_1`,
                    IncI1_1_Alpha)

# export file as csv

x6 <- column_to_rownames(x6, var = "id")
infantis_plasmid <- x6
write.csv(infantis_plasmid, "~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/infantis_plasmid.csv")

# generate another file

x7 <- x5 %>% select(ColpVC_1, ColRNAI_1, `IncA/C2_1`,
                    IncFIA_1, `IncFIB(AP001918)_1`,
                    `IncFIB(K)_1_Kpn3`, `IncFIC(FII)_1`,
                    IncI1_1_Alpha)
####################################################################
####################################################################
####################################################################

# PCA cluster

data2 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/pca_infantis/cluster2.csv")

d8 <- data2 %>% select(-X1)
d9 <- d8 %>% mutate(pca_cluster = ifelse(cluster == "1", "Cluster 1", "Cluster 2"))
d10 <- d9 %>% select(id, pca_cluster)


# merge datasets

d11 <- left_join(d6, d10, on = "id")
d11b <- left_join(d11, d3b, on = "id")
d12 <- left_join(d11b, abx7, on = "id")
d13 <- left_join(d12, x7, on = "id")

# substitude NAs to zeros

d13[is.na(d13)] <- 0

# export the data

d14 <- column_to_rownames(d13, var = "id")
infantis_plasmid_abx <- d14
write.csv(infantis_plasmid_abx, "~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/infantis_plasmid_abx.csv")
```