---
title: "Supervised search for loci Infantis"
author: "Joao Carlos Gomes-Neto"
date: "3/7/2021"
output: html_document
---

Load packages

```{r, include = FALSE}
# Load packages

library(tidyverse)
library(skimr)
library(RColorBrewer)
library(gridExtra)
library(lattice)
library(ggpubr)
library(vegan)
library(reshape2)
library(ggrepel)
library(ggnewscale)
library(forcats)
library(naniar)
library(data.table)
library(rARPACK)
library(logisticPCA)
library(cluster)
library(factoextra)
library(NbClust)
library(plotly)
library(visdat)
library(ggtree)
library(Rtsne)
```
generating the population structure metadata file

```{r, include = FALSE}
# enter metadata

d1 <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/metadata_cleaned_final_new.csv')

# rename variables

d2 <- d1 %>% select(id, collection_date, source)

# Combine all years less than 2015 into one group

d2 <- d2 %>%  mutate_all(na_if, "missing")

# change NA in the year column to zero

d2$collection_date[is.na(d2$collection_date)] <- 0

# transform year to numeric

d2 <- d2 %>% mutate(collection_date = as.numeric(collection_date))

# create a new column called Year

d2 <- mutate(d2, year = ifelse(collection_date == 2016, "2016",
                                    ifelse(collection_date == 2017, "2017",
                                            ifelse(collection_date == 2018, "2018",
                                                      ifelse(collection_date == 2019, "2019",
                                                             "<= 2015"
                                           )))))

# check for missing values 

vis_miss(d2)

# filter only needed columns 

d3b <- d2 %>% select(id, year, source)

##########################################################################
##########################################################################
##########################################################################

#############################################

# BAPS1

baps <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/fastbaps_partition_baps_prior_l6.csv')

# Changing column names 

colnames(baps)[1:2] <- c("id", "baps_1") 

# Select colunms id and baps_1
b1 <- baps %>% 
              select(id, baps_1)


d1 <- b1

#############################################################################################

# ST

# enter mlst data 
mlst <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/salmonellast_output.csv')

# QC the data

skim(mlst)

# Generate the id column 

mlst$id2 <- sapply(strsplit(as.character(mlst$FILE),'_'), "[", 1)

# Select columns of interest

s1 <- mlst %>%
          select(id2, ST) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") %>%
                  rename(id = id2)

# st

s1$st <- ifelse(s1$ST == 32, "ST32", "Other STs")

d2 <- s1

d2 <- d2 %>% select(-ST)

#############################################################################################

# CGMLST

# Enter SISTR results

sistr <- read_csv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/sistr_all.csv')

# QC the data 

skim(sistr)

# Generate the id column 

sistr$id <- sapply(strsplit(as.character(sistr$genome),'_'), "[", 1)

# Select columns 

sis1 <- sistr %>%
            select(id, cgmlst_ST, serovar_cgmlst) %>%
            mutate_all(na_if, "-") %>%
              mutate_all(na_if, "?") 

sis1$serovar <- ifelse(sis1$serovar_cgmlst == "Infantis", "Infantis",
                            "Other serovars")

sis1 <- mutate(sis1, cgmlst = ifelse(cgmlst_ST %in% 2242423463, "cgMLST 2242423463",
                                            "Other cgMLSTs"))

d3 <- sis1

d3 <- d3 %>% select(id, cgmlst)

#############################################################################################

# merge datasets

d4 <- left_join(d1, d2, on = "id")
d5 <- left_join(d4, d3, on = "id")

# replace NA for STs

d7 <- d5 %>% mutate(st = replace_na(st, "Other STs"))

##########################################################################################
##########################################################################################
##########################################################################################

####################################################################

# PCA cluster

data2 <- read_csv("~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/pca_infantis/cluster2.csv")

d8 <- data2 %>% select(-X1)
d9 <- d8 %>% mutate(pca_cluster = ifelse(cluster == "1", "Cluster 1", "Cluster 2"))
d10 <- d9 %>% select(id, pca_cluster)


# merge datasets

d11 <- left_join(d7, d10, on = "id")
d12 <- left_join(d11, d3b, on = "id")

#######################################################################################
#######################################################################################
# enter Rtab file and select genes needed

d1 <- read_tsv('~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/gene_presence_absence.Rtab')

# set Genes as rownames

d1 <- column_to_rownames(d1, var = "Gene") 

d1$Gene <- NULL

# Transpose it

d2 <- transpose(d1)

# Add column and rownames

rownames(d2) <- colnames(d1)
colnames(d2) <- rownames(d1)

# Sum up each row

d3 <- d2 %>%
  colSums()

d3b <- as.data.frame(d3)
d3b <- rownames_to_column(d3b, "genes")

# Find genes that are not core (99% or more of genomes)

d4 <- d3b %>% 
      mutate(prop = (d3/2851)*100) %>%
      filter(prop >= 15 & prop < 82)

list_of_genes <- d4$genes

# get the accessory table

d5 <- d2 %>%
      select(list_of_genes)

# Reset id to colnames

d6 <- d5
d6 <- rownames_to_column(d6, "id")

# merge datasets

d13 <- left_join(d12, d6, on = "id")
d13b <- select(d13, -starts_with("group_"))
genes_to_exclude <- c("rhsC", "yicJ_2", "lpfB_2", "ygcS", "nirC", "rluE", "yigB",
                      "wzxC", "sspH2", "hyaB_2", "yicJ_1", "oadG_1", "iolB", 
                      "ompN_2", "uvrA", "mhpE_2", "ushA", "gsk", "oadB_3", "yfdG", "malE",
                      "hybO", "iolG_2", "mhpE_1", "oadB_2", "papC_2", "algC_2",
                      "nanM", "tufA_2", "napA", "tufA_1", "manC1_2", "yjhB_2", "ccmA", "ccmB",
                      "cfiA", "fosA")

d13c <- d13b %>% select(-starts_with(genes_to_exclude))

# export  the data

d14 <- column_to_rownames(d13c, var = "id")
infantis_all_loci <- d14
write.csv(infantis_all_loci, "~/Documents/frontiers_paper_salmonella_newport_typhimurium/data/infantis/input_data/infantis_all_loci.csv")
```